### ISSUE TITLE
MTU check

### ISSUE THREAD

**Issue by jemcek** [jemcek/packETH#1]
If built packet is larger than MTU on the interface the packet can not be sent. The problem is, you don't get any warning. Maybe a message in the status bar would be an option?

**Comment by kayb94** [comment]
Can confirm. I had this once and I think it took me at least half an hour before I realized that I had forgotten to set the MTU to a high enough value ;)

**Comment by jemcek** [comment]
solved in 3.0. 
in case the sent functiono return -1, an error dialog is raised with the notice for MTU check
