### ISSUE TITLE
In GUI icmpv6 generated packet size is limited to 570bytes 

### ISSUE THREAD

**Issue by ciberp** [jemcek/packETH#15]
In GUI for generating icmpv6 packets seems to be limitation on max number of chars in "Message body 0x" field. Fix is need in:

gtk_entry_set_max_length (GTK_ENTRY (entry214), 1024);      <——  this number 1024 should be increased to somethng larger, like 3000

**Comment by jemcek** [comment]
Allowed up to 5000 bytes of payload data. This is the limitations of the text_entry dialog box. Up to 9000 will be possible with icmpv6 dialog redesign [https://github.com/jemcek/packETH/issues/16]
