### ISSUE TITLE
Missing pthreadvc.dll on windows 10 x64

### ISSUE THREAD

**Issue by phgachoud** [jemcek/packETH#20]
Sorry for the ignorance, but there was a missing pthreadvc.dll error. I tried to fix it with [these ](http://www.dlldownloader.com/pthreadvc-dll/) instructions, but was unable to register it. 
Any help for the process of dependencies installation would be greatly appreciated.

**Comment by jemcek** [comment]
Windows version was never really supported and due to a bug with fragmentation flag I would suggest not to use it. Try Linux version instead. 

http://packeth.sourceforge.net/packeth/FAQ.html
