### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by leonpollak** [jemcek/packETH#24]
I don't know whether it is mine or common...
While compiling I receive the following error:
gcc  -g -O2   -o packETH src/main.o src/support.o src/interface.o src/callbacks.o src/function.o src/function_send.o src/loadpacket.o src/savepacket.o  -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lharfbuzz -lfontconfig -lfreetype -lgthread-2.0 -pthread -lglib-2.0  -lm
/usr/bin/ld: src/function_send.o:/home/leonp/packETH-master/src/function_send.c:58: multiple definition of `iftext'; src/callbacks.o:/home/leonp/packETH-master/src/callbacks.c:68: first defined here
IMHO, both are defined without "static" or "extern", which causes the error.
Can I declare both statics or one external?

**Comment by jemcek** [comment]
Which OS are you running? Maybe there is a problem with particular (new) distro?

**Comment by Feo-d-oR** [comment]
> Which OS are you running? Maybe there is a problem with particular (new) distro?

This is a GCC10 (and, probably, older) default behavior with -fno-common set. Take a look at pull request, this problem is fixed right there… https://github.com/jemcek/packETH/pull/22

**Comment by jemcek** [comment]
merged #22
