### ISSUE TITLE
GCC-10 stringop-truncation warnings cause CLI build to fail

### ISSUE THREAD

**Issue by jbromley** [jemcek/packETH#25]
When running make in the `cli` directory on an Ubuntu 21.04 system with gcc 10.3.0-1ubuntu1 I get the numerous of the following type of warning about `strncpy`. Since `-Werror` is active, these warnings cause the build to fail.

```
In file included from /usr/include/string.h:519,
                 from cli_send.c:27:
In function ‘strncpy’,
    inlined from ‘interface_setup’ at cli_send.c:1576:5:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: error: ‘__builtin_strncpy’ output may be truncated copying 15 bytes from a string of length 19 [-Werror=stringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |       __glibc_objsize (__dest));
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~
```
The full build log is included in the attached build log.

[build.log](https://github.com/jemcek/packETH/files/7549849/build.log)

**Comment by jemcek** [comment]
It seems that GCC 10 (and 9) uses much stricter checking of string arguments. 

For the quick solution just remove the -Werror in line 34 of the Makefile. I checked and works fine. 

Patch to correct this warning will follow.

**Comment by jbromley** [comment]
I have patched a couple of files to make it compile and it appears to work, though I haven't thoroughly tested everything, since basically anything that copies strings or data from memory was affected. If you like I can make a pull request so you can review the code.

**Comment by jemcek** [comment]
yes please, do a pull request so I can take a look.

**Comment by vipinpv85** [comment]
Faced similar issue, cross checking the same the easiest fix to substitute `strncpy` with `memcpy`. The gcc compiler is sharing the warning/error since strncpy is expected to copy over src strings which are '\0' terminated. But at `cli_send.c:1576:5` this is not happening

**Comment by jemcek** [comment]
thanks @vipinpv85 and @jbromley for this, replaced strncpy with memcpy, will close.
