### ISSUE TITLE
Port GUI to GTK3

### ISSUE THREAD

**Issue by qarkai** [jemcek/packETH#31]
Are there any plans since GTK2 is EOL?

**Comment by jemcek** [comment]
huh, if this is the case then this should be done, yes. 

Are there many changes, how difficult is it to do the migration?

**Comment by jemcek** [comment]
Is the GTK3 the way to go or even GTK4?

**Comment by qarkai** [comment]
> Are there many changes, how difficult is it to do the migration?

A lot of changes (mostly in glade files) but doesn't seem to be difficult. A couple widgets are gone and have to replaced.


> Is the GTK3 the way to go or even GTK4?

GTK3 is still supported. It's up to you but I guess it's easier to upgrade GTK2->GTK3->GTK4 than GTK2->GTK4.
