### ISSUE TITLE
'make' and 'make install' fails on OS X 10.13.4

### ISSUE THREAD

**Issue by 065673** [jemcek/packETH#9]
make
_**make 
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
depbase=`echo src/callbacks.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DPKGDATADIR=\"/usr/local/share/packeth/\" -I.  -g -O2 -Wall -Wmissing-prototypes -Wmissing-declarations -Wunused -D_REENTRANT -I/usr/local/Cellar/gtk+/2.24.32_2/include/gtk-2.0 -I/usr/local/Cellar/gtk+/2.24.32_2/lib/gtk-2.0/include -I/usr/local/Cellar/pango/1.42.4/include/pango-1.0 -I/usr/local/Cellar/harfbuzz/1.8.8/include/harfbuzz -I/usr/local/Cellar/graphite2/1.3.12/include -I/usr/local/Cellar/pango/1.42.4/include/pango-1.0 -I/usr/local/Cellar/fribidi/1.0.5/include/fribidi -I/usr/local/Cellar/atk/2.28.1_2/include/atk-1.0 -I/usr/local/Cellar/cairo/1.14.12/include/cairo -I/usr/local/Cellar/pixman/0.34.0_1/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.13.0/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.35/include/libpng16 -I/usr/local/Cellar/gdk-pixbuf/2.36.12/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/libpng/1.6.35/include/libpng16 -I/usr/local/Cellar/glib/2.56.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/opt/icu4c/include  -g -O2 -MT src/callbacks.o -MD -MP -MF $depbase.Tpo -c -o src/callbacks.o src/callbacks.c &&\
	mv -f $depbase.Tpo $depbase.Po
src/callbacks.c:47:10: fatal error: 'linux/sockios.h' file not found
#include <linux/sockios.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [src/callbacks.o] Error 1
make: *** [all] Error 2**_
---------------------------

make install
depbase=`echo src/callbacks.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DPKGDATADIR=\"/usr/local/share/packeth/\" -I.  -g -O2 -Wall -Wmissing-prototypes -Wmissing-declarations -Wunused -D_REENTRANT -I/usr/local/Cellar/gtk+/2.24.32_2/include/gtk-2.0 -I/usr/local/Cellar/gtk+/2.24.32_2/lib/gtk-2.0/include -I/usr/local/Cellar/pango/1.42.4/include/pango-1.0 -I/usr/local/Cellar/harfbuzz/1.8.8/include/harfbuzz -I/usr/local/Cellar/graphite2/1.3.12/include -I/usr/local/Cellar/pango/1.42.4/include/pango-1.0 -I/usr/local/Cellar/fribidi/1.0.5/include/fribidi -I/usr/local/Cellar/atk/2.28.1_2/include/atk-1.0 -I/usr/local/Cellar/cairo/1.14.12/include/cairo -I/usr/local/Cellar/pixman/0.34.0_1/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.13.0/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.35/include/libpng16 -I/usr/local/Cellar/gdk-pixbuf/2.36.12/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/libpng/1.6.35/include/libpng16 -I/usr/local/Cellar/glib/2.56.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/opt/icu4c/include  -g -O2 -MT src/callbacks.o -MD -MP -MF $depbase.Tpo -c -o src/callbacks.o src/callbacks.c &&\
	mv -f $depbase.Tpo $depbase.Po
src/callbacks.c:47:10: fatal error: 'linux/sockios.h' file not found
#include <linux/sockios.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [src/callbacks.o] Error 1

**Comment by jemcek** [comment]
OSX is not supported really. One version was done for OSX some time ago, but is pretty out of date. Check the packETH homepage for more details.
